# Error Handling

### Task 1 

- A try catch and finally blocks were used to understand exception handling 
with system exceptions like DivideByZero Exception.

### Task 2 

- A try catch and finally block to catch exceptions like IndexOutRangeExceptions to catch index out of range.

### Task 3 

- A custom exception is created with class and custom message. 
- Here InvalidAgeInput Excepotion was thrown and catch block printed the custom messsage

### Task 4 

- KeyValueNotFound Exception is just thrown in the catch block. 
- AppDomain was initialised and MyHandler Function was created to handle unhandled exceptions in this case KeyValueNotFoundException. 
- This My handler function globally cathed the unhandled exception

### Task 5

The Same like Task 4. With the help of Myhandler StackTrace been printed